### ISSUE TITLE
Extension doesn't start on Fedora Asahi Linux Arm64

### ISSUE THREAD

**Issue by janvhs** [swift-server/vscode-swift#644]
**Describe the bug**
The LSP won't start on Linux arm64.
It shows the following message:

```
Activating Swift extension failed: Failed to find swift executable
```

and shows the stack trace:

```
2023-11-28 17:42:11.599 [info] ExtensionService#_doActivateExtension sswg.swift-lang, startup: false, activationEvent: 'workspaceContains:Package.swift'
2023-11-28 17:42:11.620 [error] Activating extension sswg.swift-lang failed due to an error:
2023-11-28 17:42:11.620 [error] Error: Failed to find swift executable
	at $x (/home/jan/.vscode/extensions/sswg.swift-lang-1.7.0/dist/extension.js:75:8119)
	at async v.n (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:124:6205)
	at async v.m (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:124:6168)
	at async v.l (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:124:5625)
```

**To Reproduce**
1. Install the extension
2. See error

**Expected behavior**
Start the LSP.

**Environment**
 - OS: Fedora Asahi Remix 39
 - Swift version (output of `swift --version`): Swift version 5.8.1 (swift-5.8.1-RELEASE) Target: aarch64-unknown-linux-gnu
 - Visual Studio Code version: 1.84.2  1a5daa3a0231a0fbba4f14db7ec463cf99d7768e  arm64
 - vscode-swift version: v1.7.0

**Additional context**
Keep in mind that I am on a MacBook Air running an arm64 Linux version.

**Comment by adam-fowler** [comment]
If you open a terminal inside VSCode and type `/bin/sh -c "LCMESSAGES=C type swift` what is the output?

**Comment by janvhs** [comment]
Sorry, for the late response.
It's the following:

```
$ /bin/sh -c "LCMESSAGES=C type swift"
swift ist /usr/bin/swift
```

I installed VSCode and Swift as RPM packages.

**Comment by janvhs** [comment]
It's basically the same:

```
swift is /usr/bin/swift
```

Is auto-discovering the Swift executable a supported feature?

**Comment by janvhs** [comment]
Super random and hope you do not mind the ping, but thanks @adam-fowler for teaching me the LC_MESSAGES trick. I used it several times since you taught me its existence. Is really handy!
